
[functions.create-ticket-from-storage]
enabled = true
verify_jwt = true
import_map = "./functions/create-ticket-from-storage/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-ticket-from-storage/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-ticket-from-storage/*.html" ]

[functions.process-ticket]
enabled = true
verify_jwt = true
import_map = "./functions/process-ticket/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/process-ticket/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/process-ticket/*.html" ]
